ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS file_data  BYTEA,
  ADD COLUMN IF NOT EXISTS file_name  VARCHAR(120),
  ADD COLUMN IF NOT EXISTS mime_type  VARCHAR(80);

ALTER TABLE technical_certificates
  ADD COLUMN IF NOT EXISTS file_data  BYTEA,
  ADD COLUMN IF NOT EXISTS file_name  VARCHAR(120),
  ADD COLUMN IF NOT EXISTS mime_type  VARCHAR(80);
